### ISSUE TITLE
Fix off-duty intervals

### ISSUE THREAD

**Issue by iharsuvorau** [AutomatedProcessImprovement/Simod#64]
Subtract from the activity duration the intervals in which the resource is not working (using the calendars discovered for that resource).

Similar implementation in WTA
https://github.com/AutomatedProcessImprovement/waiting-time-analysis/blob/ced90337515306cfe23b3707e883ccc2a588e85e/src/wta/waiting_time/resource_unavailability.py#L88

- [x] implementation
- [x] testing

**Comment by iharsuvorau** [comment]
@david-chapela I've pushed changes for off-duty computation. With debugger testing ( :o ), 60 out of 90 intervals are unchanged and the rest are reduced. To me it seems like it's going in the right direction. 

Here's the output running `LoanApp_sequential_9-5_diffres_filtered` with the changes.

[offduty_20221117_125009_63C2412B_1DA7_4117_9277_3A2BDB9DAC61.zip](https://github.com/AutomatedProcessImprovement/Simod/files/10030801/offduty_20221117_125009_63C2412B_1DA7_4117_9277_3A2BDB9DAC61.zip)

Here's like it was before without taking the resource calendar into consideration:

[no_offduty_20221117_130456_FB7486A8_90DD_4659_8DD7_B91B3458ADA9.zip](https://github.com/AutomatedProcessImprovement/Simod/files/10030825/no_offduty_20221117_130456_FB7486A8_90DD_4659_8DD7_B91B3458ADA9.zip)

**Comment by david-chapela** [comment]
It's probably working, but I'm not sure with those results. In fact, for this log, the activity duration estimation is worse, but it makes sense:
- There are not many activity instances that got the duration extended because the resource went off-duty in the middle of its execution (so we don't have much to correct in this log).
- The calendar discovery is missing 1h in some resources, so that hour gets subtracted from the activity duration when it wasn't actually off-duty time.

I'll create a new simulation in which we can check it better.

**Comment by iharsuvorau** [comment]
@david-chapela Pushed more updates. The previous time off-duty was taken into account only for differentiated resource. This update should use off-duty for pooled and undifferentiated resources as well.

**Comment by david-chapela** [comment]
Okkei, we can test them next day that we're both in the office.

If you work into this before we meet, try to execute this log and send me the JSON parameters and the simulated log:
[LoanApp_sequential_9-5_weird_durations.csv.gz](https://github.com/AutomatedProcessImprovement/Simod/files/10043566/LoanApp_sequential_9-5_weird_durations.csv.gz)
[LoanApp_sequential_9-5_weird_durations.xes.gz](https://github.com/AutomatedProcessImprovement/Simod/files/10043567/LoanApp_sequential_9-5_weird_durations.xes.gz)
